//
// Created by Beatriz Gavilan on 13/01/2023.
//

#ifndef PROJETO_SO_2_CODES_H
#define PROJETO_SO_2_CODES_H

#define CODE_REGISTER_PUBLISHER 1
#define CODE_REGISTER_SUBSCRIBER 2
#define CODE_CREATE_MBOX 3
#define CODE_ANSWER_CREATE_MBOX 4
#define CODE_REMOVE_MBOX 5
#define CODE_ANSWER_REMOVE_MBOX 6
#define CODE_LIST_MBOX 7
#define CODE_ANSWER_LIST_MBOX 8
#define CODE_PUBLISHER_SEND_MSG 9
#define CODE_SUBSCRIBER_RECEIVE_MSG 10

#endif //PROJETO_SO_2_CODES_H
